### ISSUE TITLE
Lights don't sync 2-way

### ISSUE THREAD

**Issue by rubenstolk** [pgerke/homebridge-freeathome-local-api#12]
When I switch off a light using my physical busch jaeger buttons, the status doesn't reflect in homebridge.

**Comment by pgerke** [comment]
Which version are you using? This one should be fixed with 0.4.0-pre.

**Comment by rubenstolk** [comment]
Oh - oops - I checked the main branch and didn't see a new version. My bad! Will check it out now!

**Comment by pgerke** [comment]
Perfect!
