### ISSUE TITLE
RGBW lighting fixture control with DALI DT8 and air conditioning unit control with air conditioning gateway 

### ISSUE THREAD

**Issue by VadimGolovko** [pgerke/homebridge-freeathome-local-api#27]
Hi Philip!

My current smart home customer is very happy with your plugin for Homebridge since he gets an opportunity to enjoy a complete and transparent integration of the most free@home devices to Home Kit. He is lacking several features which include:

Split unit gateway to control air conditioning units. This features is very similar to the fancoil thermostat.
https://www.busch-jaeger.de/en/online-catalogue/product-overview?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=27303&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=7cf67980bfc5bca0532e73c0d4ae0d59

DALI gateway with DT8 feature to control RGBW lighting fixtures.
https://www.busch-jaeger.de/en/online-catalogue/product-overview?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=27304&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=dfc92ef545afaf748cb42fb2f843eba4

I am wondering what's the approach to implement listed above features and how long would it take to do that?
Thank you in advance!

**Comment by pgerke** [comment]
Hi Vadim,

I'm happy to hear that your customer is satistifed. Unfortunately, I have neither a split unit nor a DALI gateway available for testing. As the interaction with the SysAP is largely reverse-engineered, I don't see a viable way how to proceed with the integration. I would be happy to accept a PR for that topic though. Sorry to disappoint and thanks for your interest in the plugin!

**Comment by VadimGolovko** [comment]
Dear Philip,

I've been thinking if there is a way to implement the requested features. I
can extract a json configuration file from the existing ***@***.*** system
with DALI DT8 feature and air conditioning gateway and make the log files
in Wireshark or whatever tool is applicable for you. Along with that I
can do all the testing on site. There is also an option to support you
financially in order to do the job. I just have to negotiate that with the
customer since he is interested as an end user. If this approach is
suitable for you, please, let me know how much would you charge to add the
two features to the plugin. An upfront payment is possible in the amount of
50-60% through PayPal or by other means, which is discussable.
Looking forward to hearing from you!

**Comment by pgerke** [comment]
Dear Vadim, I'm flattered by your offer and your interest in the plugin, but I'm not convinced that this is the right way forward. Even with logs and traces, I cannot guarantee the success of the project. In my efforts to extend the plugin I've already hit an unexpected roadblock on several occasions. I'm not sure your customer would appreciate that outcome, especially if money has changed hands, right? There is also the question of a proposed timeline and the other typical project management questions. If we do this, we should do it right and be clear on everybody's expectations. Let me think about it, I'll get back to you.
