### ISSUE TITLE
Motion detectors remain active

### ISSUE THREAD

**Issue by pgerke** [pgerke/homebridge-freeathome-local-api#31]
Occasionally, motion detectors are not reset after they have been triggered but remain active indefinitely. I don't have a reliable way to reproduce the behavior.

**Comment by floriangrotz** [comment]
I can confirm @pgerke 
Hallway Motion  (Motion Sensor ABB700D97FB8 (ch0000)) updated characteristic MotionDetected -> true
Then it don´t turn to "false" again.

**Comment by floriangrotz** [comment]
It seem that there are only "movement" detected - and the channel does not say "no momevent"
My motion senor trigger every 13-15 seconds a channel notification.
<img width="775" alt="movement" src="https://user-images.githubusercontent.com/63972904/209965135-0588f044-b6fe-4a81-b2a1-94983ffc4a9f.png">

In parallel I have another motion senor from a Netatmo Welcome Camera. 
This motion sensor say after 17-18 seconds of "motion" then a fallback to "no motion"

-> Solution: When no channel notification after 18 seconds then reset to "no motion"

**Comment by pgerke** [comment]
Ok well, so it's not a bug really, but rather a design decision by B+J it seems. I'll add an automatic reset. Might make the reset timer configurable.... 🤔

**Comment by floriangrotz** [comment]
I guess the intention from BJ is to use the motion sensor to trigger an event on their own UI (as I do for my "night light")

<img width="1224" alt="delay" src="https://user-images.githubusercontent.com/63972904/209981212-3da5b530-8621-4914-b36b-fb74f11d83a6.png">

The timer config to reset the motion sensor might be a good thing as delays might occure in different environments and so everybody can fine tune. 

Global:
- PRO: Less effort to configure
- CON: When users have more motion sensor it can interfer

Device Specific:
- PRO: Exact configuration of devices possible
- CON: Much effort

Ideally: A global value which I can override per device (sadly most effort for you)

**Comment by pgerke** [comment]
I published the preview version `v1.4.2-i31.0` to the `issue-31` tag on [npm](https://www.npmjs.com/package/homebridge-freeathome-local-api/v/1.4.2-i31.0) that adds automatic reset with a default timeout of 20s. Please feel free to check it out, I'd be very interested in any feedback!

**Comment by pgerke** [comment]
The fix is available as [v1.4.3](https://www.npmjs.com/package/homebridge-freeathome-local-api/v/1.4.3) and tagged to the `issue-31` tag. Could you please confirm the motion sensor is resetting now?
