### ISSUE TITLE
How to enable SSL?

### ISSUE THREAD

**Issue by korneliuscode** [pgerke/homebridge-freeathome-local-api#34]
**Describe Your Problem:**
Sorry was opening this by accident. Anyways, it still might be interesting to describe how the initially enable ssl for the sysap local API.

**Comment by pgerke** [comment]
You *can* use the plugin with SSL but you'll need to disable TLS verification because the SysAP is using a self-signed certificate.
![image](https://user-images.githubusercontent.com/44918997/204637080-9d813a0d-c37a-4cbb-87e4-a43198d7da89.png)

**Comment by pgerke** [comment]
Also, note to self: Add this to the documentation... 🙈

**Comment by korneliuscode** [comment]
And this needs to be created once initially. 
![7076E82E-A4CA-449E-A5E4-FE1135AD0315](https://user-images.githubusercontent.com/7031553/204638874-fc80ead6-dec6-423a-882c-ac1264771cc8.jpeg)

love your plug-in btw!

**Comment by pgerke** [comment]
I added a paragraph about TLS to the README.
