### ISSUE TITLE
Support free@home scenes and light groups

### ISSUE THREAD

**Issue by pgerke** [pgerke/homebridge-freeathome-local-api#38]
As a user I want to trigger scenes that have been created in free@home.

NB: In the current implementation of free@home, the scenes are treated as pseudo devices. It is not possible to find out via the local API which free@home devices are included in a scene. So with the implementation of this ticket, it will be possible to trigger scenes like pressing a button.

**Comment by pgerke** [comment]
Extended the scope of the ticket to light groups.

**Comment by pgerke** [comment]
Published a pre-release version to npm: https://www.npmjs.com/package/homebridge-freeathome-local-api/v/1.5.0-pre.1

Scenes are working nicely, light groups not so much. The state of a light group is not reflected correctly on the panel. This needs some additional work I guess... Unit tests also need to be extended.

**Comment by korneliuscode** [comment]
I tried the new version, works great. The problem is just that the devices don’t show up in the HomeKit app.

**Comment by pgerke** [comment]
That's strange... The scenes and light groups should show up in the default room. Works for me at least...
![image](https://user-images.githubusercontent.com/44918997/210105447-69279b55-b189-46ea-8885-4f6866ec1a00.png)

**Comment by floriangrotz** [comment]
Maybe cross connected to #48 - as Scenes have the prefix FFF

**Comment by korneliuscode** [comment]
Given it shows up on homebridge I assume an issue between homebridge and HomeKit. Therefore should work in the plug-in. Perhaps I have to reinstall every time new devices are added (not owning a HomePod).

**Comment by pgerke** [comment]
Scenes are dont in #39, light groups still to be done.

**Comment by pgerke** [comment]
I'm giving up on the light groups. When I'm sending the same updates I'm recieving when I'm triggering the light groups from the free@home app from Apple Home, the lights are going on, but the light group remains off in free@home. This leads to inconsistent states and very bad user experience in mixed operation. I can only assume that some magic is happening in the SysAP that is not visible on the local API.
