### ISSUE TITLE
Issues with 4,3 Zoll RTR - Change of Temperature not possible / Current Temperature not shown

### ISSUE THREAD

**Issue by floriangrotz** [pgerke/homebridge-freeathome-local-api#42]
Problem witht the Support of the 4,3 Display RTR

Changing Temperature:

[29/12/2022, 12:54:14] [My free@home Setup] Office RTR (Room Temperature Controller ABB700DB6452 (ch0010)) set characteristic TargetTemperature -> 20
[29/12/2022, 12:54:14] [My free@home Setup] Received HTTP 403 status code unexpectedly: 
[29/12/2022, 12:54:14] [homebridge-freeathome-local-api] This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside write handler for characteristic: Received HTTP 403 status code unexpectedly: . See https://homebridge.io/w/JtMGR for more info.

Current Temperature are not shown
see attachment

Happy to help to make it work

**Environment:**

* **Plugin Version**: 1.4.1
* **Homebridge Version**: 1.60
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Rasp

**Comment by floriangrotz** [comment]
![IMG_0470](https://user-images.githubusercontent.com/63972904/209948154-494008fd-53e7-49be-8bbc-55c1ad870c0c.jpg)

**Comment by floriangrotz** [comment]
The first three are from an RT with a 4,3 Zoll Display
<img width="777" alt="RTR_1" src="https://user-images.githubusercontent.com/63972904/209970643-33d62111-04aa-4578-8a2a-5f4d113677fd.png">
<img width="792" alt="RTR_2" src="https://user-images.githubusercontent.com/63972904/209970654-8bf3717b-f44a-4581-a49c-fe5bdf06ef5d.png">
<img width="765" alt="RTR_3" src="https://user-images.githubusercontent.com/63972904/209970675-9a2c8aca-0b8a-44d2-8042-de855ce0d593.png">

The next three from a regular RT with small LCD Display
<img width="832" alt="sRTR_1" src="https://user-images.githubusercontent.com/63972904/209970748-ee9c62a1-0ca1-48cc-a197-9f56e8889d2b.png">
<img width="821" alt="sRTR_2" src="https://user-images.githubusercontent.com/63972904/209970761-a7fe1cf7-6c08-40f4-afea-239da371e2b1.png">
<img width="780" alt="sRTR_3" src="https://user-images.githubusercontent.com/63972904/209970778-afb84c05-2dd5-4e48-b892-55d2f5475f04.png">

**Comment by pgerke** [comment]
Ok, it seems like B+J is using other data points to provide the temperature values in the 4.3" panel with the integrated RTR while re-using the functionID from the "normal" RTR. 'Interesting' design choice... Could you please add a device config for the 4.3" panel with the RTR so I can get an overview of the functionIDs, datapoints and pairingIDs they are using. Please refer to https://github.com/pgerke/homebridge-freeathome-local-api/wiki/Retrieving-the-Configuration-for-a-device-from-the-System-Access-Point to learn how you can retrieve a device configuration from your System Access Point.

**Comment by floriangrotz** [comment]
Attached the Json
[response_1672411870395.json.txt](https://github.com/pgerke/homebridge-freeathome-local-api/files/10325211/response_1672411870395.json.txt)

**Comment by pgerke** [comment]
Thanks for providing the config. This confirms what I feared... B+J is using other data points to provide characteristice in the 4.3" RTR compared to the "regular" room temperature controllers but they're using the same function ID...

**Comment by floriangrotz** [comment]
So, a hope for a fix? :)

**Comment by pgerke** [comment]
There's always hope 😉 
But I'd like to consider a few options (e.g. add resilience, pairing ID look-up, ...) before I decide on how to proceed here.

**Comment by pgerke** [comment]
Fixed with [v1.4.4](https://www.npmjs.com/package/homebridge-freeathome-local-api/v/1.4.4).

**Comment by floriangrotz** [comment]
Works like a charm ❤️
