### ISSUE TITLE
Add support for Windows / Door Sensor

### ISSUE THREAD

**Issue by floriangrotz** [pgerke/homebridge-freeathome-local-api#43]
Add support for  

Wireless Window Sensors 
6222/1 AP-64-WL

Wireless Universal Sensor
6222/2 AP-64-WL

Have the devices on my own and can support.

**Comment by pgerke** [comment]
I'd need the sample configuration for each of the sensors before I can consider the request. Please refer to https://github.com/pgerke/homebridge-freeathome-local-api/wiki/Retrieving-the-Configuration-for-a-device-from-the-System-Access-Point to learn how you can retrieve a device configuration from your System Access Point.

**Comment by floriangrotz** [comment]
Added the Window Sensor (States Open, Closed, Tilted)
[WINDOW_response_1672412383885.json.txt](https://github.com/pgerke/homebridge-freeathome-local-api/files/10325248/WINDOW_response_1672412383885.json.txt)

Added the Universalmelder (Door) - (States Open, Closed)
[DOOR_response_1672412529246.json.txt](https://github.com/pgerke/homebridge-freeathome-local-api/files/10325247/DOOR_response_1672412529246.json.txt)

**Comment by pgerke** [comment]
Thanks for providing the config. Looking at the homebridge API, I think the best option would be to use a [contact sensor](https://developers.homebridge.io/#/service/ContactSensor). That would mean the tilted state cannot be indicated, as the contact sensor is simply binary.

**Comment by pgerke** [comment]
Just to be on the safe side, both the door and the window were closed when you pulled the configs, right?

**Comment by floriangrotz** [comment]
Both were closed 

We could also use ["Window"](https://developers.homebridge.io/#/service/Window) and ["Door"](https://developers.homebridge.io/#/service/Door)

Both have the difference that the Windows Sensor gets the data how the knob on the Window is turned. 
The Universal Sensor has a simple open/close.

**Comment by pgerke** [comment]
Sure, but Window and Door also have a mandatory Target State characteristic that I cannot disable. So you would for example be able to specify the degree to which the door shall be opened but that would obviously never happen. Not sure I like that from a user experience point of view...

**Comment by floriangrotz** [comment]
Attached the Com Log

Door seems pretty simple
<img width="599" alt="Door_Com" src="https://user-images.githubusercontent.com/63972904/210091588-77f8bc70-1166-4691-83e1-acec31d96ce0.png">

Windows - open
Door Position 100 - open
Door Position 33 - tilted
<img width="572" alt="Window_Com_open" src="https://user-images.githubusercontent.com/63972904/210091727-592141a4-f56b-445f-afb8-e9a453c8a40d.png">

Windows - closed
Door Position 0 - closed
<img width="603" alt="Windows_Com_closed" src="https://user-images.githubusercontent.com/63972904/210091766-2e7b45f9-ff77-4ac9-addb-e00050a48cb1.png">
