### ISSUE TITLE
Add support for Smoke Detectors

### ISSUE THREAD

**Issue by floriangrotz** [pgerke/homebridge-freeathome-local-api#48]
Smoke Detectors are not shown in the HomeApp

Experimental Support is switched on 

I have connected four Smoke Detectors via Alarm Stick (Wireless)

I will post attached the log of the Device / JSON

**Comment by floriangrotz** [comment]
[response_1672576989543.json.txt](https://github.com/pgerke/homebridge-freeathome-local-api/files/10328771/response_1672576989543.json.txt)

**Comment by pgerke** [comment]
When I startet creating the plugin, there was a restriction that supported B+J hardware device serials start with `ABBxxxxxxxxx`, which is apparently not the case anymore. I'll remove the corresponding check in the device discovery routine and the detectors should be recognized.

**Comment by pgerke** [comment]
Can you confirm the device is recognized in [v1.4.2-i48.0](https://www.npmjs.com/package/homebridge-freeathome-local-api/v/1.4.2-i48.0)?

**Comment by floriangrotz** [comment]
Installed it - sadly don’t show up

**Comment by pgerke** [comment]
> Installed it - sadly don’t show up

Can you please attach the startup log from Homebridge? The plug-in config (without the credentials of course) might also be useful.

**Comment by pgerke** [comment]
I spent some time yesterday creating a SysAP mock so I can now emulate devices from a config file. With the config you provided and using the plugin version mentioned above the smoke sensor was recognized, when the experimental accessories are enabled:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/44918997/210387605-5a30fb4b-e88d-4992-8f50-aad6ca252ac3.png">

![image](https://user-images.githubusercontent.com/44918997/210385751-99db7b0a-7492-4764-a076-3b394679b2f6.png)

Setting the value for `odp0000` to `1`, Apple Home even notified me about the mock smoke it detected: 

![image](https://user-images.githubusercontent.com/44918997/210386569-9a8fe067-6130-416c-8808-9cfd1bf0cf16.png)

Could you check again?

**Comment by floriangrotz** [comment]
However - NOW i see it as well :/

But - Now also a few more "acutators" show up. 
I see now a ton more Acutators :/ 
![IMG_0515](https://user-images.githubusercontent.com/63972904/210398071-370abf34-a311-4228-9b5b-a96dc47c6697.PNG)
![IMG_0516](https://user-images.githubusercontent.com/63972904/210398086-d54ae294-fe82-49cd-a7cb-6d03e6bb19c2.PNG)


coming from here
![hue](https://user-images.githubusercontent.com/63972904/210398127-8c1c9961-b04a-448c-bb1a-c68453bdc5b5.png)

I own an "Alarm Stick" where all Smoke Detectors are wireless connected to. This is transparent / don´t show up (which is a good thing)

I´ve checked the prefixes:

ABB - free at home 
BEE - Hue acutators
A00 - Media Player / Sonos
FFF - Scenes / Groups
087 - HomeTouch IP
600 - Siemens Bosch Homeconnect
E11 - Alarm Unit (e.g. Smoke Detectors)

**Comment by floriangrotz** [comment]
Maybe it is a possibility to make it configurable in the future when we know what to do with the other stuff - for now ABB and E11 are enough :)

**Comment by pgerke** [comment]
> I´ve checked the prefixes:
> 
> ABB - free at home
> BEE - Hue acutators
> A00 - Media Player / Sonos
> FFF - Scenes / Groups
> 087 - HomeTouch IP 600 - Siemens Bosch Homeconnect
> E11 - Alarm Unit (e.g. Smoke Detectors)

Is this a list you gathered from your devices or is it some part of the B+J spec that I missed? There *was* a part in the official spec, but it has been removed or at least I can't find it anymore.

> Maybe it is a possibility to make it configurable in the future when we know what to do with the other stuff - for now ABB and E11 are enough :)

Sure... Removing the prefix check was just a quick way to isolate the root cause...

**Comment by floriangrotz** [comment]
I found it on the SysAP Devices, scenes and groups - Functions page during scrolling through my devices and checking the serial numbers for anomalies.

**Comment by pgerke** [comment]
> FunFact - the Hue Switches seems to function in Homekit - but it is redundant as I connected the Hue Hub directly via Homekit. In some setups it might be helpful.

That's actually cool and very nice to know! But I'll restrict it to the `ABB` and `E11` prefixe range for now. I'd rather not introduce untested features in a fix.

**Comment by pgerke** [comment]
The fix is available as [v1.4.2](https://www.npmjs.com/package/homebridge-freeathome-local-api/v/1.4.2) and tagged to the `issue-48` tag. Could you please confirm the smoke sensor is recognized correctly?
