### ISSUE TITLE
Question regarding sensors shown as switches

### ISSUE THREAD

**Issue by Rubske70** [pgerke/homebridge-freeathome-local-api#56]
Hi,

I'm playing around with the new feature included in v1.5.0-pre.6 that shows sensors as switches in HomeKit.
This basically seems to work but one thing is not clear to me, think I'm doing something wrong but not sure.

a switch can be touched in 2 ways you can push the top side and the bottom side. But I didn't find a way to use both the top and the bottom touch within HomeKit.

You can assign single press, double press and long press but this only seems to apply to the down press on the actual sensor, could find how to use the up press.

e.g. turn light on with top press and switch it of again with the down press.

Am i doing something wrong or is this just not possible?

By the way thanks for this great plugin!!!

Regards

Rob

**Plugin Version**: 1.5.0 -pre.9
* **Homebridge Version**: 1.6.0

**Comment by pgerke** [comment]
Hi Rob, happy to hear you like the plugin! Regarding your questions:

> a switch can be touched in 2 ways you can push the top side and the bottom side. But I didn't find a way to use both the top and the bottom touch within HomeKit.

True. The System Access Point exposes the sensor as a single device. There are no separate events, channels, or datapoints for the upper and lower sides of the sensor. 

> You can assign single press, double press and long press but this only seems to apply to the down press on the actual sensor, could find how to use the up press.

Also true. The event sent by the SysAP doesn't discriminate between a long, a short, or a double press. So whenever an event is received, the plugin will trigger a single press. 

Sorry I don't have better news for you, the implementation of the sensor events is one of the parts that I'm least happy with when it comes to the (in general pretty great) local API.

One related caveat regarding the sensors if you plan to use the sensor events to trigger stuff in Apple Home: The SysAP only sends  an event, if the sensor input had an effect on the free@home system. Turning off a light switch that already was off will not trigger an event.

**Comment by Rubske70** [comment]
Hi,

Thanks for your answers, sorry to hear I wil not be able to use the Free@Home buttons to trigger other homekit devices / lights. (due to the current limitations in the events send by the SysAP)

Hopefully they will implement more into the API along the way. 

Br

Rob
