### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by rubenstolk** [pgerke/homebridge-freeathome-local-api#6]
**Describe The Bug:**
I tried to setup this plugin but it fails to authenticate with my bridge, throwing an error

**To Reproduce:**
I simply installed the plugin, configured it with host, user and password and set tls to false.

**Expected behavior:**
I've been using https://www.npmjs.com/package/homebridge-freeathome-local for some time with the same details and that one does not have authentication issues. (It has other issues, hence I'm hoping that this new plugin will make my life easier!)

**Logs:**

```
[6/16/2022, 10:08:26 PM] [free@home / local] Authentication information is missing or invalid.
[6/16/2022, 10:08:26 PM] [free@home / local] Device discovery failed Error: Authentication information is missing or invalid.
    at r.SystemAccessPoint.<anonymous> (/usr/lib/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/webpack:/freeathome-local-api-client/src/system-access-point.ts:363:15)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/index.js:1:155821
    at new Promise (<anonymous>)
    at n (/usr/lib/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/index.js:1:155566)
    at r.SystemAccessPoint.processRestResponse (/usr/lib/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/index.js:1:159405)
    at r.SystemAccessPoint.<anonymous> (/usr/lib/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/webpack:/freeathome-local-api-client/src/system-access-point.ts:173:17)
    at Generator.next (<anonymous>)
    at u (/usr/lib/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/index.js:1:155623)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[6/16/2022, 10:08:26 PM] [free@home / local] Unexpected response received
```

**Comment by pgerke** [comment]
Hi and thanks for bringing this to my attention!

Could it be that you are using the name of your user account instead of the user ID? The first you are using to authenticate to the web UI of the System Access Point and it is also used by the plugin you mentioned and it's predecessor, while the user ID is a guid. You can see the user ID in the free@home next app, or you can get it from the System Access Point Swagger endpoint at `http://{SysAP IP or Host}/swagger/users`.

**Comment by rubenstolk** [comment]
Alright, tried it out, and it does work now! I'm facing one other issue but maybe we can create a separate issue:

Whenever I change the brightness of one of my dimmer lights, it says in the logs that it's changing the brightness to that value but immediately after it also changes it to 100%, hence my lights almost always go to full brightness...

**Comment by pgerke** [comment]
Happy to hear your issue is resolved. 

The other issue sounds strange, doesn't happen on my setup. But let's discuss this in another issue.

**Comment by Mischmasch44** [comment]
> 
> 
> The user ID is a guid that you can obtain from the free@home next app or from the System Access Point Swagger endpoint at `http://{SysAP IP or Host}/swagger/users` (it's the string beneath the user account name).

Hi,
I couldn't find the user ID anywhere in the free@home next app. The link `http://{SysAP IP or Host}/swagger/users` just outputs an error. Do I need to be the installer of the free@home system for that?

**Comment by pgerke** [comment]
# free@home next App
You can find the local API options in the burger menu -> free@home Settings -> Locale API
![image](https://user-images.githubusercontent.com/44918997/196006012-5ebf6d10-ba13-4a76-8e2d-90c471ed2987.png)


# Swagger Endpoint
Works for me. Can you be a little more specific as to what error you are encountering? You don't need to be authenticated to use the endpoint.
![image](https://user-images.githubusercontent.com/44918997/196005861-2181e344-6c49-4a40-927a-03bd4f07fc4c.png)

**Comment by Mischmasch44** [comment]
Hi sorry for the late response,
> You can find the local API options in the burger menu -> free@home Settings -> Locale API 

Unfortunalty, I can't find the described submenu "Lokale API", as seen here:
![IMG_2431](https://user-images.githubusercontent.com/84414896/196772485-bc3edb0c-76a4-4f10-bc0e-8616ca363e43.jpeg)

> Works for me. Can you be a little more specific as to what error you are encountering? You don't need to be authenticated to use the endpoint. 

Or when I try reaching the endpoint, I only get an error message:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/84414896/196771110-eef455fe-9c5c-4bdb-b9e2-4173a95b46ff.png">
Maybe I'm overlooking something simple. Thanks for your help.

**Comment by Mischmasch44** [comment]
So apparently I have the old Sys AP (6200 AP-101), [which doesn't support the local API feature (german)](https://community.busch-jaeger.de/frage-ansehen/wo-kann-ich-die-localapi-aktivieren). Is there any other way to solve this problem? If not, I will probably have to return to Henry Spanka's version.

**Comment by pgerke** [comment]
I'm really sorry, but there is no workaround that I am aware of. Local API is only supported on SysAP 2.0 running firmware version 2.6.0 or newer. I know that is a major pain point among the SysAP version 1 owners who feel that they are being "punished" as the early adopters. I'm keeping my fingers crossed that Busch + Jäger comes around and if they do, I'll do my best to support SysAP v1 as well.

**Comment by Mischmasch44** [comment]
Thanks for your effort :)
