### ISSUE TITLE
Question regarding configuration / authentication

### ISSUE THREAD

**Issue by pgerke** [pgerke/homebridge-freeathome-local-api#61]
Dear Philip,I don’t know how to get the plug-in working and I found no solution. My problem is the configuration does not work.I enabled the local API and also created a certificate. But I think, I don’t understand which IDs, username etc to enter. I tried everything…name": "My ***@***.*** Setup",
  "host": "????",
  "user": "12345678-9ACB-DEF0-1234-56789ABCDEF0",
  "password": "admin Passwort???",In particular „Host“ and „password“ are my problems. User, I guess, is the long name I find in the local API settings of ***@***.*** Maybe you are so kind to help me out. Sorry for bothering you, but I did not find any explanation. Best regardsMaxAm 07.03.2023 um 22:24 schrieb Philip Gerke ***@***.***>:﻿
Hi @MaxV85, shades and blinds are experimentally supported at the moment. As you can see on the example of this issue there are still a couple of quirks to be worked out with the implementation. I do plan to continue working on them but I don't have a timeline. Also, I don't have ***@***.*** blinds for testing, so I can't really tell you how easy it'll be to get the user experience right.
I cannot help you with the decision whether or not to use the plugin for the blinds in it's current state. You don't really have anything to lose except for your time. If you do try out the plugin and encounter an issue, please feel free to share any details that might help me improve the implementation.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

_Originally posted by @MaxV85 in https://github.com/pgerke/homebridge-freeathome-local-api/issues/37#issuecomment-1464944089_

**Comment by pgerke** [comment]
Duplicate of / related to #6

**Comment by pgerke** [comment]
Dear @MaxV85,

assuming the local API is active on you SysAP, you'll need three things in order to enable Homebridge to create a connection: 

1) The hostname or IP address of the System Access Point. This can be a string like `sysap` (which is the default BTW) or something like `192.168.178.xxx`. 
2) The user ID of the local API user: This is usually a UUID or a user name. Please check out [this comment](https://github.com/pgerke/homebridge-freeathome-local-api/issues/6#issuecomment-1279825457) for further details.
3) The password of that user. If you get the user ID from the free@home app, then you should use the password of the user that you use to login to the app with.

You don't need a certificate and to my knowledge there is no option to even provide a custom TLS certificate to the SysAP. So you can either chose to disable TLS altogether or disable the TLS certificate verification in the connection settings.

**Comment by MaxV85** [comment]
Dear Philip,

i got it, I was confused by the host „name“, but I tried the IP and it worked. 
thanks a lot.

this can be closed from my point of view.

**Comment by pgerke** [comment]
Happy to hear your issues are resolved!
