### ISSUE TITLE
Hue support

### ISSUE THREAD

**Issue by ditistijn** [pgerke/homebridge-freeathome-local-api#69]
**Is your feature request related to a problem? Please describe:**
Hue devices won't show up that have been added to the F@H app using the bridge functionality

<img width="394" alt="image" src="https://github.com/pgerke/homebridge-freeathome-local-api/assets/23241774/513dbbd8-d902-42d2-8164-1bfa14d43052">

**Describe the solution you'd like:**
I would like the Phillips Hue fixtures to show in the Home app using the same plugin so I got everything centralized.

**Comment by pgerke** [comment]
What would be the benefit implementing Hue support in this plugin over using a Homebridge plugin for Hue like for example https://github.com/ebaauw/homebridge-hue?
